apps/login/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^$', views.login_index, name= 'user_index'),
    url(r'^register$', views.register, name= 'register'),
    url(r'^login$', views.login, name= 'login'),
  
]


 

travelbuddy2/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^', include('apps.login.urls', namespace = 'login_ns')),
    url(r'^travels/', include('apps.travel.urls', namespace='travel_ns')),
]

apps/login/models.py
from __future__ import unicode_literals
import bcrypt
import hashlib
import re
import datetime


from django.db import models

# Create your models here.

class UserManager(models.Manager):
    def get_all(self):
        total_users = User.objects.all()
        return total_users
    def get_current(self, user_id): 
        current_user = User.objects.get(id=user_id)
        print(current_user)
        return current_user

    def validate (self, postData):
    #this method ensures that what the user inputs is valid
    
        regex_name = re.compile(r'^[a-zA-Z\s]{3,100}$') #{minum length, maximum length}
        error_arr = []
    # error = 0 #this is to check if everything below passes! It can also be used as a boolean
        if not regex_name.match(postData['first_name']):
            error_arr.append("Please enter a valid name! It must be 3 characters long and have no numbers!")
        if not postData['password'] == postData['confirm']: #if these don't match up
            error_arr.append("Your passwords do not match!")
        if len(postData['password']) < 8:
            error_arr.append("Your password must be at least 8 characters long!")
        if self.username_exist(postData): #take postData and pass it to the emailExist method
            error_arr.append("You have already registered with this username!")

        return error_arr
    
    def username_exist(self, postData):
        findUsername = User.objects.filter(username=postData['username'])
        if findUsername: #this line equates to: if findEmail has value, or is true
            return True #if it is true, the email already exists
        else:
            return False #if false, it will become registered 
    
    def register(self, postData):
        self.create( #we want to create one row in Users that has all these fields so we keep it together
            first_name = postData['first_name'],  
            username = postData['username'],
            password = bcrypt.hashpw(postData['confirm'].encode(), bcrypt.gensalt())
        )
    
    def login_user(self, postData):
        user_info = self.filter(username=postData['username']) #find the User row that contains the entered email
        if not user_info: #if user_info is false...
            return False #if the email isn't there, get outta here!
        print ('- First instance of user_info -')
        print (user_info) #so we can see if it's the correct user we're talking about
        #user_info currently gives you an array which has a dictionary inside
        user_info = user_info[0] #traverse to the first index in the list
        print ('- Second instance of user_info -')
        print (user_info) #now we get object!
        pw_hash = user_info.password.encode() #this set pw_hash to equal the password for the user object we just printed in the terminal
        if pw_hash == bcrypt.hashpw(postData['password'].encode(), pw_hash): #the second pw_hash is being used to check if it matches the postData password
            return True
        return False
    
    def set_session(self, postData): #with this method, we will be retrieving an id and sending to our views.py
        #we already know that the inputed email exists, so now we want to find associated user info with the line below
        #Also, since we know that we will be getting a list with one item, we can skip setting this to find_user[0] and say .first() instead
        find_user = self.filter(username=postData['username']).first()
        return find_user.id #this sends returns the id value

class User(models.Model):
    first_name = models.CharField(max_length=100)
    username = models.CharField(max_length=45)
    password = models.CharField(max_length=100)
    confirm = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()

apps/login/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from .models import User
from ..travel.models import Trip

# Create your views here.

def login_index(request):
    total_users = User.objects.get_all()
    context = {
        'all_users': total_users
    }
    print context
    return render(request, 'login/index.html', context)

def register(request):
    error_arr_message = User.objects.validate(request.POST)
    if len(error_arr_message) > 0: #if my error_arr_message is not empty...
        for message in error_arr_message: #loop through the array and add them all to "messages" and it is what we use in our html
            messages.add_message(request, messages.ERROR, message)
        return redirect ('/')
    if User.objects.username_exist(request.POST):
        messages.add_message(request, messages.ERROR, "Username already exits!")
        return redirect ('/')
    User.objects.register(request.POST) #pass the POST dictionary to the UserManager register method
    request.session['user_id'] = User.objects.set_session(request.POST) #this will log in the user without making go through the login form
    print (request.session['user_id']) 
    return redirect ('travel_ns:travel_index')

def login(request):
    if "user_id" in request.session: #this says is the user_id key (from the login method when we set the session) in session?
        messages.add_message(request, messages.ERROR, "You are already logged in!")
        return redirect('travel_ns:travel_index')

    login_attempt = User.objects.login_user(request.POST) #this says go to User, then it's objects, then the method login_user
    if not User.objects.username_exist(request.POST): #did they input an email that's in the database?
        messages.add_message(request, messages.ERROR, "Username is incorrect!")
        return redirect('/')
        #now we check to see if the password matches the email with the code below!
    if not login_attempt: #aka if login_attempt == False
        messages.add_message(request, messages.ERROR, "Password is incorrect!")
        return redirect('/')
    #now let's set the session!
    request.session['user_id'] = User.objects.set_session(request.POST) #this sets the session so we can access this user's info as long as they are logged in
    print (request.session['user_id']) #user_id is a key that we just created. this will go to list_app views for the index!
    return redirect('travel_ns:travel_index') #reroute to my success page

apps/login/templates/login/index.html
<html>

<head>
    <title>Login/Registration</title>
    {% load staticfiles %}
	<link rel="stylesheet" href="{% static '/login/css/stylesheet.css' %}" media="screen" charset="utf-8">
</head>

<body>
    <div class="wrapper">
        <div class="header">
            <h1>Welcome!</h1>
        </div>

        <div class="home-blocks">
            <div class="create-login">
                <form class="boxes" action= '{% url "login_ns:register" %}' method='POST'>
                        {% csrf_token %} 

                        <fieldset>
                        <legend>Register</legend>    
                        
                        <div class="input-group"><label for="first_name">Name: </label><input type="text" name="first_name"></div>
                        <div class="input-group"><label for="username">Userame: </label><input type="text" name="username"></div>
                        <div class="input-group"><label for="password">Password: </label><input type="text" name="password"></div>
                        <div class="alert-pw">*Password must be atleast 8 characters</div>
                        <div class="input-group"><label for="confirm">Confirm PW: </label><input type="text" name="confirm"></div>
                        <input type="submit" value="Register!">
                        <div class="error">
                            <ul>
                            {% for idx in messages %}
                                <li>{{ idx}}</li>
                            {% endfor %}
                            </ul>
                        </div>
                         </fieldset>

                </form>
            </div>

            <div class="login">
                <form class="boxes" action= '{% url "login_ns:login" %}' method='POST'>
                        {% csrf_token %} 
                        <fieldset>
                        <legend>Login</legend>    
                        <div class="input-group"><label for="username">Username: </label><input type="text" name="username"></div>
                        <div class="input-group"><label for="password">Password: </label><input type="text" name="password"></div>
                        <input type="submit" value="Login!">
                        </fieldset>
                </form>
            </div>
        </div>
        <!--<div class="contentBox">
         <h1>Current Users:</h1>
                
                <table>
                    
                    <tr>
                        <th>User First Name</th>
                        <th>Username</th>
                        <th>User ID</th>
                
                    </tr>
                    {% for idx in all_users %}
                    <tr>
                        <td>{{idx.first_name}} </td>
                        <td>{{idx.username}} </td>
                        <td>{{idx.id}} </td>
                   
                        
                    </tr>
                    {% endfor %}
                </table>
            </div>-->
        
   </div>
    
</body>

</html>