apps/travel/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns =[
	#sets dashboard as home page in travels dir 
	url(r'^$', views.travel_index, name= 'travel_index'),

    url(r'^create$', views.add_item, name= 'add' ),
    url(r'^create_item$', views.create_item, name= 'create'),
    url(r'^logout$', views.logout, name= 'logout' ),
    url(r'^destination/(?P<item_id>\d+)$', views.view_trip, name= 'view'), 
    

    url(r'^add/(?P<item_id>\d+)$', views.add_wishlist, name= 'add_wishlist')


]

travelbuddy2/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^', include('apps.login.urls', namespace = 'login_ns')),
    url(r'^travels/', include('apps.travel.urls', namespace='travel_ns')),
]

apps/travel/models.py
from __future__ import unicode_literals
import bcrypt
import hashlib
import re
from datetime import datetime
from ..login.models import User
from django.db import models

# Create your models here.
class TripManager(models.Manager):
    def get_all_data(self, session_id): #this is coming from travel_index
        user_info = User.objects.all()
        item_info = self.all()
        current_user = User.objects.get_current(session_id)
        wishlist =  Trip.objects.find_wishlist(session_id)
        other_people_wl = self.other_wishlist(session_id)

        all_data = {
            'user_info' : user_info,
            'item_info' : item_info,
            'current_user' : current_user,
            'wishlist' : wishlist,
            'other_wishlist' : other_people_wl
        }
        return all_data

    def make_item(self, postData, session_id):
        current_user_obj = User.objects.get(id=session_id)#session_id is an entire object
        self.create(
            destination = postData['item_name'],
            plan = postData['trip_description'],
            start_date = postData['start_date'],
            end_date = postData['end_date'],
            created_by = current_user_obj #this is entering the appropriate fields for the item we created
        )
        new_item_id = self.filter().latest('id')#this will get the item's id that we just created in the lines above
        print(new_item_id)
        print(postData['item_name'])
        self.add_wishlist(new_item_id.id, current_user_obj)
        #new_item_id will be item_id in add_wishlist, same for current_user_obj, it will be user_id. ORDER MATTERS!

    def add_wishlist(self,item_id, user_id):
        item_obj = self.get(id=item_id)
        item_obj.wishlist.add(user_id)
        

    def find_wishlist(self, session_id):
        return self.filter(wishlist__id=session_id)
        #wishlist for current user

    def other_wishlist(self,session_id):
        return self.exclude(wishlist__id=session_id)

    
    def get_item_id(self, item_id):
        return self.get(id=item_id)

    def get_wishers(self, item_id, created_by_id):

        return User.objects.filter(wishlist_list=item_id).exclude(id=created_by_id)


class Trip(models.Model):
    destination = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()
    plan = models.TextField(max_length=1000)
    created_by = models.ForeignKey(User, related_name="trips_added")
    wishlist = models.ManyToManyField(User, related_name = "wishlist_list")
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = TripManager()

apps/travel/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from .models import Trip
from datetime import date
from ..login.models import User



def travel_index(request):
    session_id = request.session['user_id']#this is from the register/login set_session
    all_data = Trip.objects.get_all_data(session_id)
   
    print(request.session['user_id'])
    context = {
        'all_data' : all_data,
    }
    print(all_data)
    return render(request, 'travel/dashboard.html', context)

def add_item(request):
    return render(request, 'travel/add_trip.html')

def create_item(request):
    if len(request.POST['item_name'])< 2:
        messages.add_message(request, messages.ERROR, "Please enter a valid destination! It must be at least 2 characters long and have no numbers!")
        return redirect ('travel_ns:add')

    if request.POST['end_date'] < request.POST['start_date']:
        messages.add_message(request, messages.ERROR, "Trip to date must be after the from date.")
        return redirect ('travel_ns:add')
    Trip.objects.make_item(request.POST, request.session['user_id'])
    return redirect('travel_ns:travel_index')

def view_trip(request, item_id): 
    trip = Trip.objects.get_item_id(item_id)
    wishers = Trip.objects.get_wishers(item_id, trip.created_by_id)

    context = {
        'trip' : trip,
        'wishers' : wishers, 
        'user' : request.session
    }

    return render(request, 'travel/show_trip.html', context)

def add_wishlist(request, item_id):
    item_id=item_id
    user_id=request.session['user_id']
    print (user_id)
    Trip.objects.add_wishlist(item_id, user_id)
    return redirect('travel_ns:travel_index')

#def delete_item(request, item_id):
#    Trip.objects.delete_me(item_id)
#    return redirect('travel_ns:travel_index')

#def remove_item(request, item_id):
#    Trip.objects.remove_me(item_id, request.session['user_id'])
#    return redirect('trip_ns:travel_index')

def logout(request):
    request.session.flush() #this clears all the sessions!
    return redirect('login_ns:user_index')

    

apps/travel/templates/travel/add_trip.html
<html>

<head>
    <title>Schedule Trip</title>
    {% load staticfiles %}
	<link rel="stylesheet" href="{% static '/login/css/stylesheet.css' %}" media="screen" charset="utf-8">
</head>

<body>
    <div class="wrapper">
        <div class="nav-bar">
            <a href= '{% url "travel_ns:travel_index" %}' id="link">Home</a>
            <a href="{% url 'travel_ns:logout' %}">Logout</a>
        </div>

          <div class="error">
            <ul>
            {% for idx in messages %}
                <li>{{ idx}}</li>
            {% endfor %}
            </ul>
        </div>
                
        <div class="contentBox">
            <form class="boxes" action= '{% url "travel_ns:create" %}' method='POST'>
                    {% csrf_token %} 
                <h1>Create a New Trip!</h1>
                <hr>
                <h4>Destination: </h4><input type="text" name="item_name">
                <h4>Description: </h4><input type="text" name="trip_description">
                <h4>Start Date: <input type="date" name="start_date">
                <h4>End Date: <input type="date" name="end_date">
              
                <input type="submit" value="Add!">
                        
             </form>
        </div>      
   </div>
    
</body>

</html>

apps/travel/templates/travel/dashboard.html
<html>

<head>
    <title>Travel Dashboard</title>
    {% load staticfiles %}
	<link rel="stylesheet" href="{% static '/login/css/stylesheet.css' %}" media="screen" charset="utf-8">
</head>

<body>
    <div class="wrapper">
        <div class="header">
                <div class="nav-bar">
                    <a href="{% url 'travel_ns:logout' %}">Logout</a>
                </div>
            <h1>Hello, {{all_data.current_user.first_name}}!</h1>
        </div>

        
                
        <h2>Your Trip Schedules</h2>
            <table>
                <tr>
                    <th>Destination</th>
                    <th>Travel Start Date</th>
                    <th>Travel End Date</th>
                    <th>Plan</th>
                </tr>
                {% for user_trip in all_data.wishlist %}
                <tr>
                    <td><a href='{% url "travel_ns:view" user_trip.id %}'>{{user_trip.destination}}</a> </td>
                    <td>{{user_trip.start_date}}</td>
                    <td>{{user_trip.end_date}}</td>
                    <td>{{user_trip.plan}}</td>
                </tr>
                   
                {% endfor %}
            </table>
            
        <h2>Other User's Travel Plans</h2>
        <table>
            <tr>
                <th>Name</th>
                <th>Destination</th>
                <th>Travel Start Date</th>
                <th>Travel End Date</th>
                <th>Want You want to Join?</th>
            </tr>
            {% for other_trips in all_data.other_wishlist %}
            <tr>
                <td>{{other_trips.created_by.first_name}} </td>
                <td>{{other_trips.destination}} </td>
                <td>{{other_trips.start_date}}</td>
                <td>{{other_trips.end_date}}</td>
                <td>
                    <a href="{% url 'travel_ns:add_wishlist' item_id=other_trips.id %}">Join</a>
                </td>
            </tr>
            {% endfor %}
        </table>
        <div class="nav-bar">
            <a href= '{% url "travel_ns:add" %}' id="link">Add Travel Plan</a>
        </div>
       
        
   </div>
    
</body>

</html>

apps/travel/templates/travel/show_trip.html
<html>

<head>
    <title>View Trip</title>
    {% load staticfiles %}
	<link rel="stylesheet" href="{% static '/login/css/stylesheet.css' %}" media="screen" charset="utf-8">
</head>

<body>
    <div class="wrapper">
        <div class="nav-bar">
            <a href= '{% url "travel_ns:travel_index" %}' id="link">Home</a>
            <a href="{% url 'travel_ns:logout' %}">Logout</a>
        </div>


        <div class="destination-info">   
            <h1>{{trip.destination}}</h1>
            <ul>  
                <li>Planned By: {{trip.created_by.first_name}}</li>
                <li>Description: {{trip.plan}}</li>
                <li>Travel Date From: {{trip.start_date}}</li>
                <li>Travel Date To: {{trip.end_date}}</li>
            </ul>
        </div>
        <div class="destination-joining">
            <h2>Other users' joining the trip:</h2>
            
            <ul>
                {% for user in wishers %}
                    <li>{{user.first_name}}</li>
                {% endfor %}
            </ul>
        </div>                        
            
        </div>
   </div>
    
</body>

</html>